# Generated by Django 4.0 on 2022-01-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse_tbl',
            old_name='contact_no',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='nurse_tbl',
            old_name='e_mail',
            new_name='email',
        ),
    ]
