# Generated by Django 4.0 on 2022-02-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacc_app', '0002_rename_contact_no_nurse_tbl_contactno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse_tbl',
            name='login_id',
        ),
    ]
