# Generated by Django 4.0 on 2022-01-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacc_app', '0003_alter_vaccinationschedule_tbl_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationschedule_tbl',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vaccinationschedule_tbl',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
