# Generated by Django 4.0 on 2022-02-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacc_app', '0004_remove_user_tbl_login_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_TBL',
        ),
    ]
