# Generated by Django 4.0 on 2022-01-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacc_app', '0004_alter_vaccinationschedule_tbl_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard_tbl',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacc_app.vaccine_tbl'),
        ),
    ]
