# Generated by Django 4.0 on 2022-02-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacc_app', '0005_delete_login_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_tbl',
            name='user',
        ),
    ]
