# Generated by Django 4.0 on 2022-01-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacc_app', '0005_alter_reportcard_tbl_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_tbl',
            name='reply',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
