# Generated by Django 4.0 on 2022-01-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacc_app', '0006_alter_complaint_tbl_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_tbl',
            name='schedule',
            field=models.TimeField(),
        ),
    ]
